# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
      - Emulator
      - EmulatorInfo
      - Error
      - Optimization
    Restart:
      - Scheduler

# ==================== Daily ====================

Daily:
  menu: 'list'
  page: 'setting'
  tasks:
    Mission:
      - Scheduler
    Freebies:
      - Scheduler
      - Freebies
    ZhaoCai:
      - Scheduler
      - ZhaoCai
    Organization:
      - Scheduler
      - Organization
    DailyReward:
      - Scheduler
      - DailyReward
    DataUpdate:
      - Scheduler
      - ItemStorage
    SquadRaid:
      - Scheduler
      - SquadRaid


# ==================== Weekly ====================



# ==================== Tool ====================



