# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
      - Emulator
      - EmulatorInfo
      - Error
      - Optimization
    Restart:
      - Scheduler

# ==================== Daily ====================

Daily:
  menu: 'list'
  page: 'setting'
  tasks:
    FengRao:
      - Scheduler
      - FengRao
    SquadRaid:
      - Scheduler
      - SquadRaid
    Organization:
      - Scheduler
      - Organization
    SurvivalTrail:
      - Scheduler
      - SurvivalTrail
    Mission:
      - Scheduler
    Freebies:
      - Scheduler
      - Freebies
    ZhaoCai:
      - Scheduler
      - ZhaoCai
    DailyReward:
      - Scheduler
      - DailyReward
    DataUpdate:
      - Scheduler
      - ItemStorage




# ==================== Weekly ====================
Weekly:
  menu: 'list'
  page: 'setting'
  tasks:
    CultivationRoad:
      - Scheduler



# ==================== Tool ====================



